import{a as w,i as a,S as E}from"./assets/vendor-YT4DRQk6.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const S="48468658-42ed6d7129c3b4c82c2d48fe1",q="https://pixabay.com/api/";async function g(e,o=1,s=15){try{return(await w.get(q,{params:{key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:s}})).data}catch{throw new Error("Failed to fetch images")}}function y(e){return e.map(({webformatURL:o,largeImageURL:s,tags:n,likes:t,views:r,comments:c,downloads:v})=>`
          <li class="gallery-item">
            <a href="${s}" class="gallery-link">
              <img src="${o}" alt="${n}" loading="lazy" />
            </a>
            <div class="info">
              <p><b>Likes:</b> ${t}</p>
              <p><b>Views:</b> ${r}</p>
              <p><b>Comments:</b> ${c}</p>
              <p><b>Downloads:</b> ${v}</p>
            </div>
          </li>
        `).join("")}function P(e){e.innerHTML=""}function L(e){e.hidden=!1}function b(e){e.hidden=!0}const p=document.querySelector("#search-form"),f=document.querySelector("#gallery"),h=document.querySelector("#loader"),i=document.querySelector("#load-more");let d,m="",l=1,u=0;p.addEventListener("submit",async e=>{e.preventDefault();const o=p.query.value.trim();if(!o){a.error({title:"Error",message:"Please enter a search term.",position:"topRight"});return}m=o,l=1,u=0,P(f),i.classList.add("is-hidden"),L(h);try{const s=await g(m,l);if(u=s.totalHits,s.hits.length===0){a.warning({title:"No Results",message:"No images found. Try a different search.",position:"topRight"});return}f.innerHTML=y(s.hits),d?d.refresh():d=new E(".gallery-link"),s.hits.length<15||l*15>=u?(i.classList.add("is-hidden"),a.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):i.classList.remove("is-hidden")}catch(s){a.error({title:"Error",message:s.message})}finally{b(h)}});i.addEventListener("click",async()=>{l+=1,L(h),i.classList.add("is-hidden");try{const e=await g(m,l);f.insertAdjacentHTML("beforeend",y(e.hits)),d.refresh(),l*15>=u?(i.classList.add("is-hidden"),a.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):i.classList.remove("is-hidden"),R()}catch(e){a.error({title:"Error",message:e.message})}finally{b(h)}});function R(){const{height:e}=f.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
